#ResourceFlavor
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
  name: default-flavor
spec: {}

#ClusterQueue
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-queue
spec:
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: TryNextFlavor
  namespaceSelector: {}
  preemption:
    borrowWithinCohort:
      policy: Never
    reclaimWithinCohort: Never
    withinClusterQueue: Never
  queueingStrategy: BestEffortFIFO
  resourceGroups:
    - coveredResources:
        - cpu
        - memory
        - nvidia.com/gpu
      flavors:
        - name: default-flavor
          resources:
            - name: cpu
              nominalQuota: '4'
            - name: memory
              nominalQuota: 16Gi
            - name: nvidia.com/gpu
              nominalQuota: 0
  stopPolicy: None

#LocalQueue
--- 
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  annotations:
    kueue.x-k8s.io/default-queue: 'true'
  name: mnist-local-queue
spec:
  clusterQueue: cluster-queue
